spring:
  config:
    import: "aws-parameterstore:/cloud-architecture/prod/"

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

  cloud:
    aws:
      s3:
        bucket: cloud-architecture-files
      cloudfront:
        domain: ${CLOUDFRONT_DOMAIN}

logging:
  level:
    root: INFO
    com.example: INFO
    org.hibernate.SQL: WARN
  file:
    name: /var/log/cloud-architecture/app.log

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true

info:
  team-name: ${team-name}